# S.E.A.M HTML Generator
# Run: powershell -ExecutionPolicy Bypass -File gen_html.ps1
$outPath = "$PSScriptRoot\index.html"
$fs = [System.IO.FileStream]::new($outPath, [System.IO.FileMode]::Create, [System.IO.FileAccess]::Write)
$sw = [System.IO.StreamWriter]::new($fs, [System.Text.Encoding]::UTF8)
function WL($s) { $sw.WriteLine($s) }

WL '<!DOCTYPE html>'
WL '<html lang="en">'
WL '<head>'
WL '<meta charset="UTF-8"/>'
WL '<meta name="viewport" content="width=device-width,initial-scale=1.0"/>'
WL '<title>S.E.A.M &#8212; Audio Audition</title>'
WL '<style>'
WL '/* Fonts: use css/fonts.css + ../fonts/ in the modular index.html build (offline). */'
WL ':root{'
WL '  --bg:#1a1a2e;--bg2:#16213e;--bg3:#0f3460;--card:#1e2a45;--card2:#253352;'
WL '  --border:#2d4170;--accent:#e94560;--accent2:#f5a623;--accent3:#4ecdc4;'
WL '  --green:#52d68a;--text:#eaf0fb;--text2:#8fa3c8;--text3:#546a8a;'
WL '  --r:8px;--rs:5px;--sh:0 4px 20px rgba(0,0,0,.4);'
WL '}'
WL '*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}'
WL 'html{scroll-behavior:smooth}'
WL 'body{background:var(--bg);color:var(--text);font-family:''DM Sans'',sans-serif;font-size:14px;line-height:1.5;min-height:100vh;overflow-x:hidden}'
WL '::-webkit-scrollbar{width:6px;height:6px}'
WL '::-webkit-scrollbar-track{background:var(--bg2)}'
WL '::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px}'
WL '.app-header{background:linear-gradient(135deg,var(--bg2),var(--bg3));border-bottom:2px solid var(--accent);padding:13px 24px;display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;box-shadow:var(--sh);position:sticky;top:0;z-index:100}'
WL '.app-logo{font-family:''Space Mono'',monospace;font-size:19px;font-weight:700;letter-spacing:3px;color:var(--accent);text-shadow:0 0 20px rgba(233,69,96,.4)}'
WL '.app-logo small{color:var(--text2);font-size:10px;letter-spacing:2px;display:block;margin-top:1px;font-family:''DM Sans'',sans-serif;font-weight:400}'
WL '.header-actions{display:flex;gap:8px;align-items:center}'
WL '.btn{background:var(--card2);border:1px solid var(--border);color:var(--text);padding:7px 14px;border-radius:var(--rs);cursor:pointer;font-family:''DM Sans'',sans-serif;font-size:13px;font-weight:500;transition:all .15s;display:inline-flex;align-items:center;gap:6px;white-space:nowrap}'
WL '.btn:hover{background:var(--border);border-color:var(--accent3)}'
WL '.btn-accent{background:var(--accent);border-color:var(--accent);color:#fff}'
WL '.btn-accent:hover{background:#c73652;border-color:#c73652}'
WL '.btn-sm{padding:5px 10px;font-size:12px}'
WL '#setup-panel{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:calc(100vh - 70px);gap:24px;padding:32px 24px}'
WL '.setup-card{background:var(--card);border:1px solid var(--border);border-radius:16px;padding:46px 50px;max-width:500px;width:100%;text-align:center;box-shadow:var(--sh)}'
WL '.setup-icon{font-size:52px;margin-bottom:12px}'
WL '.setup-card h2{font-size:21px;font-weight:700;margin-bottom:10px}'
WL '.setup-card p{color:var(--text2);font-size:14px;line-height:1.75;margin-bottom:22px}'
WL '.setup-card p code{background:var(--bg3);padding:1px 6px;border-radius:3px;font-family:''Space Mono'',monospace;font-size:12px;color:#a8dadc}'
WL '.setup-card .btn-accent{font-size:15px;padding:12px 28px;width:100%;justify-content:center}'
WL '#select-status{margin-top:12px;font-size:12px;color:var(--text3);min-height:18px}'
WL '#no-fsapi-warn{display:none;background:rgba(233,69,96,.12);border:1px solid var(--accent);border-radius:var(--r);padding:12px 16px;margin-top:14px;color:var(--accent);font-size:12px}'
WL '#main-app{display:none;padding:18px 24px 60px;max-width:1400px;margin:0 auto}'
WL '.tabs-wrap{width:80%;margin:0 auto 14px}'
WL '.tabs-nav{display:flex;gap:3px;background:var(--bg2);padding:3px;border-radius:var(--r);border:1px solid var(--border);width:fit-content}'
WL '.tab-btn{background:transparent;border:none;color:var(--text2);padding:7px 22px;border-radius:var(--rs);cursor:pointer;font-family:''Space Mono'',monospace;font-size:12px;font-weight:700;letter-spacing:1px;transition:all .15s}'
WL '.tab-btn.active{background:var(--accent);color:#fff;box-shadow:0 2px 8px rgba(233,69,96,.4)}'
WL '.tab-btn:hover:not(.active){background:var(--card2);color:var(--text)}'
WL '.tab-content{display:none}.tab-content.active{display:block}'
WL '.pl-wrap{width:80%;margin:0 auto}'
WL '.pl-container{background:var(--card);border:1px solid var(--border);border-radius:var(--r) var(--r) 0 0;overflow:hidden;box-shadow:var(--sh)}'
WL '.pl-header{display:grid;grid-template-columns:40px 1fr 100px 58px 116px;padding:8px 14px;background:var(--bg3);font-family:''Space Mono'',monospace;font-size:10px;font-weight:700;letter-spacing:1px;color:var(--text2);text-transform:uppercase;border-bottom:1px solid var(--border);gap:8px;align-items:center}'
WL '.song-row{border-bottom:1px solid rgba(45,65,112,.5);user-select:none;transition:background .1s}'
WL '.song-row:last-child{border-bottom:none}'
WL '.song-row.dragging{opacity:.3}'
WL '.song-row.drag-over{box-shadow:inset 0 -3px 0 var(--accent)}'
WL '.song-row.row-playing{background:rgba(233,69,96,.04)}'
WL '.row-main{display:grid;grid-template-columns:40px 1fr 100px 58px 116px;padding:9px 14px;align-items:center;gap:8px;cursor:grab}'
WL '.row-main:hover{background:rgba(255,255,255,.025)}'
WL '.col-nr{font-family:''Space Mono'',monospace;font-size:12px;color:var(--text3);text-align:center}'
WL '.col-name{font-weight:500;font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;position:relative}'
WL '.col-name.missing{color:var(--accent2)}'
WL ".col-name.missing:hover::after{content:'Main song file missing \2014 only parts available';position:absolute;bottom:calc(100% + 4px);left:0;background:var(--card);border:1px solid var(--accent2);color:var(--accent2);font-size:11px;padding:4px 8px;border-radius:4px;white-space:nowrap;z-index:50;pointer-events:none}"
WL '.col-dur{font-family:''Space Mono'',monospace;font-size:12px;color:var(--accent3);text-align:center}'
WL '.col-parts{text-align:center}'
WL '.parts-badge{background:var(--bg3);border:1px solid var(--border);border-radius:12px;padding:2px 10px;cursor:pointer;transition:all .15s;display:inline-block;font-family:''Space Mono'',monospace;font-size:12px;font-weight:700}'
WL '.parts-badge:hover{background:var(--accent3);color:var(--bg);border-color:var(--accent3)}'
WL '.col-act{display:flex;gap:5px;align-items:center;justify-content:flex-end}'
WL '.t-btn{background:transparent;border:1px solid var(--border);color:var(--text2);border-radius:var(--rs);width:28px;height:28px;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:all .12s;font-size:11px;flex-shrink:0}'
WL '.t-btn:hover{background:var(--card2);color:var(--text);border-color:var(--accent3)}'
WL '.t-play{border-color:var(--green);color:var(--green)}'
WL '.t-play:hover{background:rgba(82,214,138,.15)}'
WL '.t-pause{border-color:var(--accent2);color:var(--accent2)}'
WL '.t-pause:hover{background:rgba(245,166,35,.15)}'
WL '.t-stop{border-color:var(--accent);color:var(--accent)}'
WL '.t-stop:hover{background:rgba(233,69,96,.15)}'
WL '.sdot{width:6px;height:6px;border-radius:50%;background:var(--green);animation:blink 1.1s infinite;flex-shrink:0}'
WL '@keyframes blink{0%,100%{opacity:1}50%{opacity:.2}}'
WL '.player-area{background:rgba(15,52,96,.3);border-top:1px solid rgba(45,65,112,.6);padding:12px 14px 14px;display:none}'
WL '.player-area.vis{display:block;animation:fadeUp .2s ease}'
WL '@keyframes fadeUp{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}'
WL '.parts-list{margin-bottom:10px}'
WL '.part-item{display:flex;align-items:flex-start;flex-direction:column;padding:4px 8px;border-radius:var(--rs);margin-bottom:3px;transition:background .1s;cursor:default}'
WL '.part-item-row{display:flex;align-items:center;gap:8px;width:100%}'
WL '.part-item:hover,.part-item.hl{background:rgba(78,205,196,.07)}'
WL '.part-item.part-playing{background:rgba(82,214,138,.07);border-left:2px solid var(--green)}'
WL '.p-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0;margin-top:1px}'
WL '.p-lbl{flex:1;font-size:12px;color:var(--text2);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'
WL '.part-item.part-playing .p-lbl{color:var(--green);font-weight:500}'
WL '.mini-bar-wrap{display:none;width:100%;margin:4px 0 2px 16px;align-items:center;gap:8px}'
WL '.mini-bar-wrap.vis{display:flex}'
WL '.mini-bar{flex:1;height:4px;background:var(--bg3);border-radius:2px;position:relative;cursor:pointer;overflow:visible}'
WL '.mini-fill{height:100%;background:var(--green);border-radius:2px;pointer-events:none}'
WL '.mini-handle{width:10px;height:10px;background:var(--green);border-radius:50%;position:absolute;top:-3px;transform:translateX(-50%);cursor:grab}'
WL '.mini-time{font-family:''Space Mono'',monospace;font-size:10px;color:var(--text3);white-space:nowrap;min-width:36px}'
WL '.seek-section{margin-top:8px}'
WL '.bricks-row{display:flex;gap:2px;height:28px;position:relative;margin-bottom:0}'
WL '.pbrick{height:100%;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:9px;font-weight:700;font-family:''Space Mono'',monospace;cursor:pointer;transition:filter .15s;position:relative;overflow:visible;user-select:none;border:1px solid rgba(255,255,255,.12)}'
WL '.pbrick:hover,.pbrick.hl{filter:brightness(1.35)}'
WL '.pbrick.active-b{box-shadow:0 0 0 2px rgba(255,255,255,.8)}'
WL '.pbrick-lbl{font-size:9px;font-weight:700;color:rgba(0,0,0,.7);pointer-events:none;overflow:hidden;white-space:nowrap;padding:0 3px}'
WL '.loop-row{position:relative;height:22px;margin-top:3px}'
WL '.loop-bw{position:absolute;transform:translateX(-50%)}'
WL '.loop-btn{background:var(--card2);border:1px solid var(--border);color:var(--text2);border-radius:11px;padding:2px 9px;font-size:10px;font-family:''Space Mono'',monospace;cursor:pointer;white-space:nowrap;transition:all .12s}'
WL '.loop-btn:hover{background:var(--bg3);color:var(--accent3);border-color:var(--accent3)}'
WL '.loop-btn.lactive{background:rgba(78,205,196,.15);border-color:var(--accent3);color:var(--accent3)}'
WL '.time-wrap{position:relative;height:18px;margin-top:8px}'
WL '.time-lbl{position:absolute;bottom:0;transform:translateX(-50%);background:var(--card2);border:1px solid var(--border);border-radius:3px;padding:1px 5px;font-family:''Space Mono'',monospace;font-size:10px;color:var(--text2);white-space:nowrap;pointer-events:none}'
WL '.seek-track{height:7px;background:var(--bg3);border-radius:4px;position:relative;cursor:pointer;overflow:visible;margin-top:1px}'
WL '.seek-fill{height:100%;background:linear-gradient(90deg,var(--accent),var(--accent2));border-radius:4px;pointer-events:none}'
WL '.seek-handle{width:13px;height:13px;background:#fff;border:2px solid var(--accent);border-radius:50%;position:absolute;top:-3px;transform:translateX(-50%);cursor:grab;box-shadow:0 0 8px rgba(233,69,96,.5)}'
WL '.seek-pct{font-family:''Space Mono'',monospace;font-size:10px;color:var(--text3);margin-top:3px;text-align:right}'
WL '.ins-line{position:absolute;top:0;bottom:0;width:3px;background:var(--accent);border-radius:2px;pointer-events:none;z-index:50}'
WL '.loop-dd{position:fixed;background:var(--card);border:1px solid var(--border);border-radius:var(--rs);box-shadow:var(--sh);z-index:500;min-width:130px;overflow:hidden;display:none}'
WL '.loop-dd.open{display:block}'
WL '.loop-opt{padding:8px 14px;cursor:pointer;font-size:12px;color:var(--text2);transition:background .1s}'
WL '.loop-opt:hover{background:var(--card2);color:var(--text)}'
WL '.loop-opt.sel{color:var(--accent3);background:rgba(78,205,196,.08)}'
WL '.footer-ctrl{width:80%;margin:16px auto 0;display:flex;align-items:flex-start;gap:20px;flex-wrap:wrap}'
WL '.cf-group{display:flex;align-items:center;gap:10px;background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:10px 16px}'
WL '.cf-group label{font-family:''Space Mono'',monospace;font-size:11px;color:var(--text2);letter-spacing:.5px;white-space:nowrap}'
WL '.cf-slider{-webkit-appearance:none;width:110px;height:4px;background:var(--bg3);border-radius:2px;outline:none;cursor:pointer}'
WL '.cf-slider::-webkit-slider-thumb{-webkit-appearance:none;width:13px;height:13px;background:var(--accent2);border-radius:50%;cursor:grab}'
WL '.cf-val{font-family:''Space Mono'',monospace;font-size:11px;color:var(--accent2);min-width:48px}'
WL '.knob-group{display:flex;flex-direction:column;align-items:center;gap:4px;background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:12px 16px}'
WL '.knob-lbl{font-family:''Space Mono'',monospace;font-size:10px;color:var(--text2);letter-spacing:.5px;text-transform:uppercase}'
WL '.knob-val{font-family:''Space Mono'',monospace;font-size:12px;color:var(--accent2);min-width:48px;text-align:center}'
WL 'canvas#speed-knob{cursor:ns-resize;display:block;touch-action:none}'
WL '.pl-totals{background:var(--card);border:1px solid var(--border);border-top:none;border-radius:0 0 var(--r) var(--r);padding:8px 14px;display:flex;gap:18px;flex-wrap:wrap;font-family:''Space Mono'',monospace;font-size:10px;color:var(--text2);justify-content:flex-end}'
WL '.tv{color:var(--accent3)}'
WL '.modal-ov{position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:1000;display:flex;align-items:center;justify-content:center;padding:20px}'
WL '.modal-ov.hidden{display:none}'
WL '.modal-box{background:var(--card);border:1px solid var(--border);border-radius:14px;max-width:740px;width:100%;max-height:87vh;overflow-y:auto;box-shadow:0 20px 60px rgba(0,0,0,.6);padding:28px 32px;position:relative}'
WL '.modal-x{position:absolute;top:14px;right:14px;background:transparent;border:1px solid var(--border);color:var(--text2);width:29px;height:29px;border-radius:50%;cursor:pointer;font-size:15px;display:flex;align-items:center;justify-content:center}'
WL '.modal-x:hover{background:var(--accent);color:#fff;border-color:var(--accent)}'
WL '.modal-box h2{font-size:17px;font-weight:700;color:var(--accent);margin-bottom:4px;font-family:''Space Mono'',monospace}'
WL '.modal-box h3{font-size:11px;font-weight:700;color:var(--accent3);margin:16px 0 5px;font-family:''Space Mono'',monospace;text-transform:uppercase;letter-spacing:1px}'
WL '.modal-box p{color:var(--text2);font-size:13px;line-height:1.7;margin-bottom:6px}'
WL '.modal-box ul{color:var(--text2);font-size:13px;line-height:1.8;padding-left:18px}'
WL '.modal-box li{margin-bottom:3px}'
WL '.modal-box code{background:var(--bg3);padding:1px 5px;border-radius:3px;font-family:''Space Mono'',monospace;font-size:11px;color:#a8dadc}'
WL '@media(max-width:900px){.tabs-wrap,.pl-wrap,.footer-ctrl{width:100%}}'
WL '@media(max-width:600px){.pl-header{display:none}.row-main{grid-template-columns:28px 1fr 62px 36px 80px;font-size:12px}.app-logo{font-size:14px}}'
WL '</style></head><body>'

$sw.Flush(); $fs.Flush()
Write-Host "CSS done: $($fs.Position) bytes"
$sw.Close(); $fs.Close()
